version: "3"

services:
  storage-service-zip:
    image: storage-service-zip:latest
    container_name: container_name-storage-service-zip
    ports:
      - "23820:23820"
    volumes:
      - ./log:/log
      - ./storage:/storage
    environment:
      - ZIP_SUCCESS_DEL_FOLDER=false
