version: "3"

services:
  storage-service-zip:
    image: image_name-storage-service-zip:latest
    container_name: container_name-storage-service-zip
    ports:
      - "23820:23820"
    volumes:
      - ./log:/log
      - ./storage:/storage #下载和压缩包存储路径
    environment:
      - API_URL=http://localhost:23820 #外网可访问的地址
      - ZIP_DOWNLOAD_EXPIRE=3600 # 压缩包下载过期时间，单位秒
      - ZIP_SUCCESS_DEL_FOLDER=false # 压缩完成后是否删除未压缩的文件
      - ZIP_MAX_DEPTH=10 # 压缩包最大深度
      - FSC_BASE_URL=https://fileuat.baigongyi.com
      - FSC_ACCESS_KEY=access_key
      - FSC_ACCESS_SECRET=access_secret
      - ZIP_DELETE_OLD_STORAGE_JOB=0 0 3 * * ? #每天3点执行删除历史数据job
      - ZIP_DELETE_OLD_STORAGE_DAY=30 #删除多少天以前的历史存储文件夹
      - ZIP_DELETE_OVERSIZE_STORAGE_JOB=0 0 1 * * ? #每天1点执行删除历史数据job
      - ZIP_DELETE_OVERSIZE_STORAGE_SIZE=10 #存储文件夹多大后删除单位GB
    restart: always
